# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/juddn/juddperft

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/juddn/juddperft

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/juddn/juddperft/CMakeFiles /home/juddn/juddperft//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/juddn/juddperft/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named juddperft

# Build rule for target.
juddperft: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 juddperft
.PHONY : juddperft

# fast build rule for target.
juddperft/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/build
.PHONY : juddperft/fast

# Manual pre-install relink rule for target.
juddperft/preinstall:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/preinstall
.PHONY : juddperft/preinstall

chessposition.o: chessposition.cpp.o
.PHONY : chessposition.o

# target to build an object file
chessposition.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/chessposition.cpp.o
.PHONY : chessposition.cpp.o

chessposition.i: chessposition.cpp.i
.PHONY : chessposition.i

# target to preprocess a source file
chessposition.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/chessposition.cpp.i
.PHONY : chessposition.cpp.i

chessposition.s: chessposition.cpp.s
.PHONY : chessposition.s

# target to generate assembly for a file
chessposition.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/chessposition.cpp.s
.PHONY : chessposition.cpp.s

diagnostics.o: diagnostics.cpp.o
.PHONY : diagnostics.o

# target to build an object file
diagnostics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/diagnostics.cpp.o
.PHONY : diagnostics.cpp.o

diagnostics.i: diagnostics.cpp.i
.PHONY : diagnostics.i

# target to preprocess a source file
diagnostics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/diagnostics.cpp.i
.PHONY : diagnostics.cpp.i

diagnostics.s: diagnostics.cpp.s
.PHONY : diagnostics.s

# target to generate assembly for a file
diagnostics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/diagnostics.cpp.s
.PHONY : diagnostics.cpp.s

engine.o: engine.cpp.o
.PHONY : engine.o

# target to build an object file
engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/engine.cpp.o
.PHONY : engine.cpp.o

engine.i: engine.cpp.i
.PHONY : engine.i

# target to preprocess a source file
engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/engine.cpp.i
.PHONY : engine.cpp.i

engine.s: engine.cpp.s
.PHONY : engine.s

# target to generate assembly for a file
engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/engine.cpp.s
.PHONY : engine.cpp.s

fen.o: fen.cpp.o
.PHONY : fen.o

# target to build an object file
fen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/fen.cpp.o
.PHONY : fen.cpp.o

fen.i: fen.cpp.i
.PHONY : fen.i

# target to preprocess a source file
fen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/fen.cpp.i
.PHONY : fen.cpp.i

fen.s: fen.cpp.s
.PHONY : fen.s

# target to generate assembly for a file
fen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/fen.cpp.s
.PHONY : fen.cpp.s

hash_table.o: hash_table.cpp.o
.PHONY : hash_table.o

# target to build an object file
hash_table.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/hash_table.cpp.o
.PHONY : hash_table.cpp.o

hash_table.i: hash_table.cpp.i
.PHONY : hash_table.i

# target to preprocess a source file
hash_table.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/hash_table.cpp.i
.PHONY : hash_table.cpp.i

hash_table.s: hash_table.cpp.s
.PHONY : hash_table.s

# target to generate assembly for a file
hash_table.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/hash_table.cpp.s
.PHONY : hash_table.cpp.s

juddperft.o: juddperft.cpp.o
.PHONY : juddperft.o

# target to build an object file
juddperft.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/juddperft.cpp.o
.PHONY : juddperft.cpp.o

juddperft.i: juddperft.cpp.i
.PHONY : juddperft.i

# target to preprocess a source file
juddperft.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/juddperft.cpp.i
.PHONY : juddperft.cpp.i

juddperft.s: juddperft.cpp.s
.PHONY : juddperft.s

# target to generate assembly for a file
juddperft.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/juddperft.cpp.s
.PHONY : juddperft.cpp.s

movegen.o: movegen.cpp.o
.PHONY : movegen.o

# target to build an object file
movegen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/movegen.cpp.o
.PHONY : movegen.cpp.o

movegen.i: movegen.cpp.i
.PHONY : movegen.i

# target to preprocess a source file
movegen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/movegen.cpp.i
.PHONY : movegen.cpp.i

movegen.s: movegen.cpp.s
.PHONY : movegen.s

# target to generate assembly for a file
movegen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/movegen.cpp.s
.PHONY : movegen.cpp.s

search.o: search.cpp.o
.PHONY : search.o

# target to build an object file
search.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/search.cpp.o
.PHONY : search.cpp.o

search.i: search.cpp.i
.PHONY : search.i

# target to preprocess a source file
search.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/search.cpp.i
.PHONY : search.cpp.i

search.s: search.cpp.s
.PHONY : search.s

# target to generate assembly for a file
search.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/search.cpp.s
.PHONY : search.cpp.s

tablegroup.o: tablegroup.cpp.o
.PHONY : tablegroup.o

# target to build an object file
tablegroup.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/tablegroup.cpp.o
.PHONY : tablegroup.cpp.o

tablegroup.i: tablegroup.cpp.i
.PHONY : tablegroup.i

# target to preprocess a source file
tablegroup.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/tablegroup.cpp.i
.PHONY : tablegroup.cpp.i

tablegroup.s: tablegroup.cpp.s
.PHONY : tablegroup.s

# target to generate assembly for a file
tablegroup.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/tablegroup.cpp.s
.PHONY : tablegroup.cpp.s

timemanage.o: timemanage.cpp.o
.PHONY : timemanage.o

# target to build an object file
timemanage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/timemanage.cpp.o
.PHONY : timemanage.cpp.o

timemanage.i: timemanage.cpp.i
.PHONY : timemanage.i

# target to preprocess a source file
timemanage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/timemanage.cpp.i
.PHONY : timemanage.cpp.i

timemanage.s: timemanage.cpp.s
.PHONY : timemanage.s

# target to generate assembly for a file
timemanage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/timemanage.cpp.s
.PHONY : timemanage.cpp.s

utils.o: utils.cpp.o
.PHONY : utils.o

# target to build an object file
utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/utils.cpp.o
.PHONY : utils.cpp.o

utils.i: utils.cpp.i
.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s
.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/utils.cpp.s
.PHONY : utils.cpp.s

winboard.o: winboard.cpp.o
.PHONY : winboard.o

# target to build an object file
winboard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/winboard.cpp.o
.PHONY : winboard.cpp.o

winboard.i: winboard.cpp.i
.PHONY : winboard.i

# target to preprocess a source file
winboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/winboard.cpp.i
.PHONY : winboard.cpp.i

winboard.s: winboard.cpp.s
.PHONY : winboard.s

# target to generate assembly for a file
winboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/winboard.cpp.s
.PHONY : winboard.cpp.s

zobristkeyset.o: zobristkeyset.cpp.o
.PHONY : zobristkeyset.o

# target to build an object file
zobristkeyset.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/zobristkeyset.cpp.o
.PHONY : zobristkeyset.cpp.o

zobristkeyset.i: zobristkeyset.cpp.i
.PHONY : zobristkeyset.i

# target to preprocess a source file
zobristkeyset.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/zobristkeyset.cpp.i
.PHONY : zobristkeyset.cpp.i

zobristkeyset.s: zobristkeyset.cpp.s
.PHONY : zobristkeyset.s

# target to generate assembly for a file
zobristkeyset.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juddperft.dir/build.make CMakeFiles/juddperft.dir/zobristkeyset.cpp.s
.PHONY : zobristkeyset.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... juddperft"
	@echo "... chessposition.o"
	@echo "... chessposition.i"
	@echo "... chessposition.s"
	@echo "... diagnostics.o"
	@echo "... diagnostics.i"
	@echo "... diagnostics.s"
	@echo "... engine.o"
	@echo "... engine.i"
	@echo "... engine.s"
	@echo "... fen.o"
	@echo "... fen.i"
	@echo "... fen.s"
	@echo "... hash_table.o"
	@echo "... hash_table.i"
	@echo "... hash_table.s"
	@echo "... juddperft.o"
	@echo "... juddperft.i"
	@echo "... juddperft.s"
	@echo "... movegen.o"
	@echo "... movegen.i"
	@echo "... movegen.s"
	@echo "... search.o"
	@echo "... search.i"
	@echo "... search.s"
	@echo "... tablegroup.o"
	@echo "... tablegroup.i"
	@echo "... tablegroup.s"
	@echo "... timemanage.o"
	@echo "... timemanage.i"
	@echo "... timemanage.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
	@echo "... winboard.o"
	@echo "... winboard.i"
	@echo "... winboard.s"
	@echo "... zobristkeyset.o"
	@echo "... zobristkeyset.i"
	@echo "... zobristkeyset.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

